// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include "config_common.h"

/* USB Device descriptor parameter */
#define VENDOR_ID       0xFEED
#define PRODUCT_ID      0x0000
#define DEVICE_VER      0x0001
#define MANUFACTURER    %MANUFACTURER%
#define PRODUCT         Whimsy Hotswap

/* key matrix size */
#define MATRIX_ROWS 4
#define MATRIX_COLS 13


#define ENCODER_RESOLUTION 2
#define ENCODERS_PAD_A { F0 }
#define ENCODERS_PAD_B { F1 }


/*
 * Keyboard Matrix Assignments
 *
 * Change this to how you wired your keyboard
 * COLS: AVR pins used for columns, left to right
 * ROWS: AVR pins used for rows, top to bottom
 * DIODE_DIRECTION: COL2ROW = COL = Anode (+), ROW = Cathode (-, marked on diode)
 *                  ROW2COL = ROW = Anode (+), COL = Cathode (-, marked on diode)
 *
 */
#define MATRIX_ROW_PINS { B0, D2, B5, F4 }
#define MATRIX_COL_PINS { B4, B7, D7, D6, D4, D5, D3, F5, B6, F6, F7, C7, C6 }

#define DIODE_DIRECTION COL2ROW


// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/








